let S:GameState=load();
function load():GameState{try{const raw=localStorage.getItem('monsterBattleV6')||localStorage.getItem('monsterBattleV5')||'{}';const old=JSON.parse(raw);const s:GameState={...fresh(),...old,version:6,owned:old.owned||{},party:old.party||[],cleared:old.cleared||[],adventCleared:old.adventCleared||[]};if(s.battle){const q=QUESTS.find(x=>x.id===s.battle!.quest);if(q)s.stamina=Math.min(s.maxStamina,s.stamina+q.cost);s.battle=null;s.page='home'}return s}catch{return fresh()}}
function save(){localStorage.setItem('monsterBattleV6',JSON.stringify(S))}
function toast(t:string){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function modal(h:string){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="sheet">${h}</div>`;document.body.appendChild(d)}
function closeModal(){document.getElementById('modal')?.remove();render()}
function stars(n:number){return '★'.repeat(n)}
function M(id:string):MonsterDef{const b=MONSTERS[id],o=S.owned[id];if(!o?.evolved||!b.evolve)return b;return{...b,name:b.evolve,rarity:b.rarity+1,hp:Math.floor(b.hp*1.2),atk:Math.floor(b.atk*1.22)}}
function chooseStarter(id:string){S.starter=id;for(const x of [id,'ember','slime','rabit'])S.owned[x]={level:1,luck:1,evolved:false};S.party=[id,'ember','slime','rabit'];save();render();modal(`<div class="reveal"><div class="avatar">${M(id).icon}</div><h2>${M(id).name} と契約！</h2><button class="bigbtn" onclick="closeModal();go('quests')">冒険を始める</button></div>`)}
function header(){return `<header><div class="topline"><div class="brand">ASTRA CROWN<small>TYPE SCRIPT v6</small></div><div class="resources"><span class="pill">RANK <b>${S.rank}</b></span><span class="pill">⚡ ${S.stamina}/${S.maxStamina}</span><span class="pill">💎 ${S.gems}</span><span class="pill">🔷 ${S.crystals}</span><span class="pill">🪙 ${S.gold}</span></div></div></header>`}
function nav(){return `<nav class="nav">${[['home','🏠','ホーム'],['quests','⚔️','クエスト'],['box','🐾','BOX'],['dex','📖','図鑑'],['gacha','✨','ガチャ'],['other','☰','その他']].map(([p,i,l])=>`<button class="${S.page===p?'active':''}" onclick="go('${p}')"><b>${i}</b>${l}</button>`).join('')}</nav>`}
function go(p:string){S.page=p;save();render()}
function render(){const a=$('#app');if(!S.starter){a.innerHTML=`<main><div class="starter-screen"><div class="starter-wrap"><h1>最初の相棒を選べ。</h1><p>モンスターを集め、育て、降臨へ挑むコマンドRPG。</p><div class="starter-grid">${['garum','livan','sylphin'].map(id=>cardStarter(id)).join('')}</div></div></div></main>`;return}a.innerHTML=header()+`<main id="main"></main>`+(S.battle?'':nav());const m=$('#main');if(S.battle)battleView(m);else{const views:Record<string,(m:HTMLElement)=>void>={home:homeView,quests:questView,box:boxView,dex:dexView,gacha:gachaView,other:otherView};(views[S.page]||homeView)(m)}save()}
function cardStarter(id:string){const u=M(id);return `<div class="starter" onclick="chooseStarter('${id}')"><div class="bigicon">${u.icon}</div><span class="rarity">${stars(u.rarity)}</span><h3>${u.name}</h3><div class="tags"><span class="tag">${u.element}</span><span class="tag">${u.tribe}</span><span class="tag role">${u.role}</span></div><div class="passive-box tiny"><b>◆ ${u.passiveName}</b><br>${u.passiveDesc}</div></div>`}
function homeView(m:HTMLElement){const lead=M(S.party[0]),o=S.owned[S.party[0]],pct=Math.min(100,S.exp/needExp(S.rank)*100),dexCount=Object.keys(S.owned).length;m.innerHTML=`<section class="hero"><div class="tiny muted">MONSTER COLLECTION × COMMAND RPG</div><h1>一体一体に、<br>使う理由を。</h1><p>章を進み、図鑑を埋め、固有パッシブを活かして降臨へ挑もう。</p><button class="bigbtn" onclick="go('quests')">クエストへ</button> <button class="btn" onclick="go('dex')">📖 図鑑 ${dexCount}/${Object.keys(MONSTERS).length}</button></section><div class="section-title"><h2>プレイヤー</h2><span class="tiny muted">${S.exp}/${needExp(S.rank)} EXP</span></div><div class="card"><b>RANK ${S.rank}</b><div class="progress"><i style="width:${pct}%"></i></div></div><div class="section-title"><h2>リーダー</h2></div><div class="card"><div class="unit-row"><div class="avatar">${lead.icon}</div><div><b>${lead.name}</b><div class="tiny muted">🍀 ${o.luck}/99 · ${lead.role}</div><div class="passive-box tiny">◆ ${lead.passiveName} — ${lead.passiveDesc}</div></div></div></div>`}
function questTile(q:QuestDef){const locked=S.rank<q.rank;return `<div class="card quest ${q.advent?'advent':''} ${locked?'locked':''}" onclick="${locked?'':`startQuest('${q.id}')`}"><div class="qicon">${q.icon}</div><div class="tiny muted">${q.stage?`${q.stage} · `:''}${q.advent?'降臨':'NORMAL'} · RANK ${q.rank}</div><h3>${q.name}</h3><div class="tiny muted">BOSS ${q.enemy}</div><div class="tags"><span class="tag">${q.element}</span><span class="tag">${q.tribe}</span><span class="tag">⚡${q.cost}</span>${S.cleared.includes(q.id)?'<span class="tag clear-tag">CLEAR</span>':''}</div>${q.gimmickText?`<div class="gimmick">⚙ ${q.gimmickText}</div>`:''}</div>`}
function questView(m:HTMLElement){const normal=CHAPTERS.map(ch=>`<section class="chapter"><div class="chapter-head"><div class="chapter-icon">${ch.icon}</div><div><div class="tiny muted">STORY AREA</div><h2>${ch.title}</h2><p>${ch.subtitle}</p></div></div><div class="grid three">${ch.questIds.map(id=>questTile(QUESTS.find(q=>q.id===id)!)).join('')}</div></section>`).join('');const advent=QUESTS.filter(q=>q.advent).map(questTile).join('');m.innerHTML=`<div class="section-title"><div><div class="tiny muted">QUEST</div><h2>通常クエスト</h2></div></div><div class="notice">章ごとにエリアを攻略。敵の属性・種族に合わせてモンスターを選ぼう。</div>${normal}<div class="section-title"><div><div class="tiny muted">ADVENT</div><h2>降臨ダンジョン</h2></div></div><div class="grid three">${advent}</div>`}
function startQuest(id:string){const q=QUESTS.find(x=>x.id===id);if(!q||S.stamina<q.cost){toast('スタミナが足りません');return}S.stamina-=q.cost;const fighters=S.party.map(id=>{const u=M(id),o=S.owned[id],max=Math.floor(u.hp*(1+(o.level-1)*.06));return{id,hp:max,maxHp:max,ult:0,guard:false}});const log=[`${q.enemy}が現れた！`];S.battle={quest:id,enemyHp:q.hp,enemyMax:q.hp,round:1,turn:0,fighters,shield:0,debuff:0,barrier:q.gimmick==='barrier'?500:0,heat:0,aura:q.gimmick==='aura'?3:0,stunned:false,log};if(fighters.some(f=>M(f.id).passive==='tailwind')){fighters.forEach(f=>f.ult=10);log.push('◆ 追い風 発動！ 味方全体の奥義+10')}if(fighters.some(f=>M(f.id).passive==='moon')){S.battle.shield=.15;log.push('◆ 月守の結界 発動！ 最初の敵攻撃を軽減')}if(fighters.some(f=>M(f.id).passive==='partyguard'))log.push('◆ 堅牢甲殻：ロックシェル生存中は味方全体を軽減');const lead=M(S.party[0]);if(lead.passive==='drop8'||lead.passive==='drop5')log.push(`◆ ${lead.passiveName}：クリア時のドロップ率UP`);save();render()}
function Q(){return QUESTS.find(x=>x.id===S.battle!.quest)!}
function active(){return S.battle!.fighters[S.battle!.turn]}
function atkVal(id:string){const u=M(id),o=S.owned[id];return Math.floor(u.atk*(1+(o.level-1)*.055))}
